---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  progressDeadlineSeconds: 180
  minReadySeconds: 0            # default, asap
  revisionHistoryLimit: 100     #keeping the previous ReplicaSets (100 count)
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: antoniosf100/mydemoapp:v3
        ports:
        - containerPort: 8080       
        readinessProbe:
          httpGet:
            path: /demo/ping
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  labels:
    run: tomcat
spec:
  selector:
    app : tomcat
  ports:
  - name: http
    port: 80         # port to access outside
    targetPort: 8080   # port where tomcat runs inside the appserver pod.
    protocol: TCP
  externalIPs:
    - 192.168.99.101
